# Generated by Django 4.2.11 on 2024-04-27 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyid', models.AutoField(db_column='CompanyID', primary_key=True, serialize=False)),
                ('companyname', models.CharField(db_column='companyname', max_length=255)),
                ('industry', models.CharField(blank=True, db_column='Industry', max_length=100, null=True)),
                ('status', models.CharField(db_column='Status', max_length=6)),
                ('location', models.CharField(blank=True, db_column='Location', max_length=255, null=True)),
                ('datecreated', models.DateField(db_column='DateCreated')),
            ],
            options={
                'db_table': 'companies',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('fundid', models.AutoField(db_column='FundID', primary_key=True, serialize=False)),
                ('fundname', models.CharField(db_column='FundName', max_length=255)),
                ('fundsize', models.BigIntegerField(blank=True, db_column='FundSize', null=True)),
                ('fundtype', models.CharField(blank=True, db_column='FundType', max_length=100, null=True)),
                ('status', models.CharField(db_column='Status', max_length=6)),
                ('datecreated', models.DateField(db_column='DateCreated')),
                ('targetenddate', models.DateField(blank=True, db_column='TargetEndDate', null=True)),
            ],
            options={
                'db_table': 'funds',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lp',
            fields=[
                ('lpid', models.AutoField(db_column='LPID', primary_key=True, serialize=False)),
                ('lpname', models.CharField(db_column='LPName', max_length=255)),
                ('location', models.CharField(blank=True, db_column='Location', max_length=255, null=True)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=100, null=True)),
            ],
            options={
                'db_table': 'lps',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ReportDoc',
            fields=[
                ('reportdocid', models.AutoField(db_column='ReportDocID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('documentpath', models.CharField(db_column='DocumentPath', max_length=255)),
                ('date', models.DateField(db_column='Date')),
            ],
            options={
                'db_table': 'report_docs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('investmentid', models.AutoField(db_column='InvestmentID', primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=100, null=True)),
                ('amount', models.BigIntegerField(blank=True, db_column='Amount', null=True)),
                ('status', models.CharField(db_column='Status', max_length=11)),
                ('date', models.DateField(db_column='Date')),
                ('companyid', models.ForeignKey(blank=True, db_column='CompanyID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.company')),
                ('fundid', models.ForeignKey(blank=True, db_column='FundID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.fund')),
            ],
            options={
                'db_table': 'investments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fundraise',
            fields=[
                ('fundraiseid', models.AutoField(db_column='FundraiseID', primary_key=True, serialize=False)),
                ('amountinvested', models.BigIntegerField(blank=True, db_column='AmountInvested', null=True)),
                ('date', models.DateField(db_column='Date')),
                ('fundid', models.ForeignKey(blank=True, db_column='FundID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.fund')),
                ('lpid', models.ForeignKey(blank=True, db_column='LPID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.lp')),
            ],
            options={
                'db_table': 'fundraises',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FinancialDoc',
            fields=[
                ('financialdocsid', models.AutoField(db_column='FinancialDocsID', primary_key=True, serialize=False)),
                ('documentpath', models.CharField(db_column='DocumentPath', max_length=255)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=100, null=True)),
                ('isprocessed', models.IntegerField(db_column='IsProcessed')),
                ('date', models.DateField(db_column='Date')),
                ('companyid', models.ForeignKey(blank=True, db_column='CompanyID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.company')),
            ],
            options={
                'db_table': 'financial_docs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('agreementid', models.AutoField(db_column='AgreementID', primary_key=True, serialize=False)),
                ('documentpath', models.CharField(db_column='DocumentPath', max_length=255)),
                ('companyid', models.ForeignKey(blank=True, db_column='CompanyID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.company')),
            ],
            options={
                'db_table': 'agreements',
                'managed': True,
            },
        ),
    ]
