# Generated by Django 4.2.11 on 2024-04-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='test',
            field=models.CharField(db_column='test', default='what', max_length=255),
            preserve_default=False,
        ),
    ]
