# Generated by Django 4.2.11 on 2024-04-27 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_agreement_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='test',
        ),
    ]
