# Generated by Django 4.2.11 on 2024-05-08 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_agreement_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='status',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='fundsize',
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('documentid', models.AutoField(db_column='DocumentID', primary_key=True, serialize=False)),
                ('documentname', models.CharField(db_column='DocumentName', max_length=255)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=100, null=True)),
                ('isprocessed', models.IntegerField(db_column='IsProcessed')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_column='DateUploaded')),
                ('companyid', models.ForeignKey(blank=True, db_column='CompanyID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.company')),
            ],
            options={
                'db_table': 'documents',
                'managed': True,
            },
        ),
    ]
