# Generated by Django 4.2.11 on 2024-05-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_document_documentpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='datecreated',
            field=models.DateField(db_column='DateCreated', null=True),
        ),
    ]
