# Generated by Django 4.2.11 on 2024-05-10 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_company_datecreated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='documentname',
            new_name='documentname',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='documentid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='uploaded_at',
            new_name='uploadedAt',
        ),
        migrations.RemoveField(
            model_name='document',
            name='isprocessed',
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.IntegerField(db_column='Status', null=True),
        ),
    ]
