# Generated by Django 4.2.11 on 2024-05-11 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_documentname_document_documentname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='documentname',
            new_name='documentname',
        ),
    ]
