# Generated by Django 4.2.11 on 2024-05-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_documentname_document_documentname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(blank=True, db_column='Status', max_length=100, null=True),
        ),
    ]
