# Generated by Django 4.2.11 on 2024-05-11 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_document_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='documentname',
            field=models.CharField(db_column='DocumentName', max_length=255),
        ),
    ]
