# Generated by Django 4.2.11 on 2024-05-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_document_documentname'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='embedding',
            field=models.JSONField(blank=True, db_column='Embedding', null=True),
        ),
    ]
